# Generated by Django 5.2.5 on 2025-08-27 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('investor', 'Investitor'), ('contractor', 'Izvođač'), ('supervisor', 'Nadzor'), ('engineer', 'Inženjer'), ('other', 'Drugo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Broj')),
                ('subject', models.CharField(max_length=255, verbose_name='Tema')),
                ('type', models.CharField(choices=[('rfi', 'Zahtjev za informacijom (RFI)'), ('claim', 'Potraživanje'), ('notice', 'Obavijest'), ('minutes', 'Zapisnik'), ('other', 'Ostalo')], max_length=20, verbose_name='Vrsta')),
                ('received_at', models.DateField(blank=True, null=True, verbose_name='Zaprimljeno')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Rok')),
                ('status', models.CharField(choices=[('open', 'Otvoreno'), ('answered', 'Odgovoreno'), ('closed', 'Zatvoreno'), ('on_hold', 'Na čekanju')], default='open', max_length=20)),
                ('body', models.TextField(blank=True, verbose_name='Sadržaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplements', to='evidencija.letter')),
                ('from_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters_sent', to='evidencija.party')),
                ('to_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='letters_received', to='evidencija.party')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidencija.project')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Opis')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='evidencija.letter')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Bilješka / Odgovor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='evidencija.letter')),
            ],
        ),
    ]
