# Generated by Django 5.2.5 on 2025-08-27 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dogadjaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255, verbose_name='Naziv događaja')),
                ('opis', models.TextField(blank=True, verbose_name='Opis')),
                ('datum', models.DateField(auto_now_add=True, verbose_name='Datum događaja')),
                ('preporucena_radnja', models.CharField(choices=[('zzi', 'Zahtjev za informacijom (ZZI)'), ('claim', 'Potraživanje'), ('notice', 'Obavijest'), ('improvement', 'Poboljšanje'), ('suggestion', 'Prijedlog'), ('other', 'Ostalo')], max_length=20, verbose_name='Preporučena radnja')),
            ],
        ),
        migrations.RemoveField(
            model_name='letter',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='from_party',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='project',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='to_party',
        ),
        migrations.RemoveField(
            model_name='note',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.CreateModel(
            name='Dopis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj', models.CharField(blank=True, max_length=50, verbose_name='Broj dopisa')),
                ('od_koga', models.CharField(blank=True, max_length=200, verbose_name='Od koga')),
                ('za_koga', models.CharField(blank=True, max_length=200, verbose_name='Za koga')),
                ('datum_zaprimanja', models.DateField(blank=True, null=True, verbose_name='Zaprimljeno')),
                ('rok', models.DateField(blank=True, null=True, verbose_name='Rok odgovora')),
                ('status', models.CharField(choices=[('open', 'Otvoreno'), ('answered', 'Odgovoreno'), ('closed', 'Zatvoreno')], default='open', max_length=20, verbose_name='Status')),
                ('sadrzaj', models.TextField(blank=True, verbose_name='Sadržaj')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dogadjaj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dopisi', to='evidencija.dogadjaj')),
            ],
            options={
                'ordering': ['rok', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Biljeska',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField(verbose_name='Bilješka / Odgovor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dopis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biljeske', to='evidencija.dopis')),
            ],
        ),
        migrations.CreateModel(
            name='Prilog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='prilozi/')),
                ('opis', models.CharField(blank=True, max_length=255, verbose_name='Opis')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dopis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prilozi', to='evidencija.dopis')),
            ],
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Party',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
