# Generated by Django 5.2.5 on 2025-08-27 11:12

import django.utils.timezone
import evidencija.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0002_dogadjaj_remove_letter_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biljeska',
            options={'verbose_name': 'Bilješka', 'verbose_name_plural': 'Bilješke'},
        ),
        migrations.AlterModelOptions(
            name='dogadjaj',
            options={'verbose_name': 'Događaj', 'verbose_name_plural': 'Događaji'},
        ),
        migrations.AlterModelOptions(
            name='dopis',
            options={'ordering': ['razuman_rok', '-created_at'], 'verbose_name': 'Dopis', 'verbose_name_plural': 'Dopisi'},
        ),
        migrations.AlterModelOptions(
            name='prilog',
            options={'verbose_name': 'Prilog', 'verbose_name_plural': 'Prilozi'},
        ),
        migrations.RemoveField(
            model_name='dopis',
            name='datum_zaprimanja',
        ),
        migrations.RemoveField(
            model_name='dopis',
            name='od_koga',
        ),
        migrations.RemoveField(
            model_name='dopis',
            name='rok',
        ),
        migrations.RemoveField(
            model_name='dopis',
            name='za_koga',
        ),
        migrations.AddField(
            model_name='dopis',
            name='poslano',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Poslano'),
        ),
        migrations.AddField(
            model_name='dopis',
            name='razuman_rok',
            field=models.DateField(default=evidencija.models.default_razuman_rok, verbose_name='Razuman rok za odgovor'),
        ),
        migrations.AddField(
            model_name='dopis',
            name='vrsta',
            field=models.CharField(choices=[('incoming', 'Ulazno'), ('outgoing', 'Izlazno')], default='incoming', max_length=20, verbose_name='Vrsta dopisa'),
        ),
    ]
