# Generated by Django 5.2.5 on 2025-08-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0003_alter_biljeska_options_alter_dogadjaj_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogadjaj',
            options={'ordering': ['broj'], 'verbose_name': 'Događaj', 'verbose_name_plural': 'Događaji'},
        ),
        migrations.AddField(
            model_name='dogadjaj',
            name='broj',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Broj događaja'),
        ),
    ]
