# Generated by Django 5.2.5 on 2025-09-11 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0004_alter_dogadjaj_options_dogadjaj_broj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaj',
            name='datum',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum događaja'),
        ),
    ]
