# Generated by Django 5.2.5 on 2025-10-07 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0005_alter_dogadjaj_datum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gradiliste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200, unique=True, verbose_name='Naziv gradilišta')),
                ('lokacija', models.CharField(blank=True, max_length=200, verbose_name='Lokacija')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gradilište',
                'verbose_name_plural': 'Gradilišta',
                'ordering': ['naziv'],
            },
        ),
        migrations.AddField(
            model_name='dogadjaj',
            name='gradiliste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dogadjaji', to='evidencija.gradiliste'),
        ),
    ]
