# Generated by Django 5.2.5 on 2025-10-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0006_gradiliste_dogadjaj_gradiliste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogadjaj',
            name='broj',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Broj događaja'),
        ),
        migrations.AddConstraint(
            model_name='dogadjaj',
            constraint=models.UniqueConstraint(fields=('gradiliste', 'broj'), name='uniq_broj_per_gradiliste'),
        ),
    ]
