# Generated by Django 5.2.5 on 2025-10-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0007_alter_dogadjaj_broj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dopis',
            options={'ordering': ['kategorija', 'rb_po_kategoriji', 'id'], 'verbose_name': 'Dopis', 'verbose_name_plural': 'Dopisi'},
        ),
        migrations.AddField(
            model_name='dopis',
            name='broj_int',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Broj dopisa (INT)'),
        ),
        migrations.AddField(
            model_name='dopis',
            name='kategorija',
            field=models.CharField(blank=True, choices=[('', '—'), ('zzi', 'ZZI'), ('potrazivanje', 'Potraživanje'), ('prijedlog', 'Prijedlog'), ('uputa_inzenjera', 'Uputa Inženjera'), ('poboljsanje', 'Poboljšanje'), ('obavijest', 'Obavijest'), ('dopis', 'Dopis')], default='', max_length=30, verbose_name='Vrsta dopisa'),
        ),
        migrations.AddField(
            model_name='dopis',
            name='rb_po_kategoriji',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Redni broj (po vrsti dopisa)'),
        ),
        migrations.AlterField(
            model_name='dopis',
            name='broj',
            field=models.CharField(blank=True, max_length=50, verbose_name='Broj dopisa (staro)'),
        ),
    ]
