# Generated by Django 5.2.5 on 2025-10-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0008_alter_dopis_options_dopis_broj_int_alter_dopis_broj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dopis',
            options={'ordering': ['broj_int', 'id'], 'verbose_name': 'Dopis', 'verbose_name_plural': 'Dopisi'},
        ),
        migrations.AddField(
            model_name='dopis',
            name='broj_int',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Broj dopisa (INT)'),
        ),
        migrations.AlterField(
            model_name='dopis',
            name='broj',
            field=models.CharField(blank=True, max_length=50, verbose_name='Broj dopisa (staro)'),
        ),
        migrations.AddConstraint(
            model_name='dopis',
            constraint=models.UniqueConstraint(fields=('dogadjaj', 'broj_int'), name='uniq_dopis_broj_per_dogadjaj'),
        ),
    ]
