# Generated by Django 5.2.5 on 2025-10-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0008_alter_dopis_options_dopis_broj_int_dopis_kategorija_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dopis',
            options={'ordering': ['poslano', 'id'], 'verbose_name': 'Dopis', 'verbose_name_plural': 'Dopisi'},
        ),
        migrations.RemoveField(
            model_name='dopis',
            name='rb_po_kategoriji',
        ),
        migrations.AddField(
            model_name='dopis',
            name='oznaka',
            field=models.CharField(blank=True, max_length=50, verbose_name='Oznaka (po vrsti dopisa)'),
        ),
    ]
