# Generated by Django 5.2.5 on 2026-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0010_merge_0008_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogadjaj',
            name='status',
            field=models.CharField(choices=[('otvoreno', 'Otvoreno'), ('odgovoreno', 'Odgovoreno'), ('zatvoreno', 'Zatvoreno')], default='otvoreno', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='dopis',
            name='kategorija',
            field=models.CharField(blank=True, choices=[('', '—'), ('zzi', 'ZZI'), ('potrazivanje', 'Potraživanje'), ('obavijest_o_potrazivanju', 'Obavijest o Potraživanju'), ('prijedlog', 'Prijedlog'), ('uputa_inzenjera', 'Uputa Inženjera'), ('poboljsanje', 'Poboljšanje'), ('obavijest', 'Obavijest'), ('dopis', 'Dopis')], default='', max_length=30, verbose_name='Kategorija dopisa'),
        ),
    ]
