# Generated by Django 5.2.5 on 2026-02-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidencija', '0011_dogadjaj_status_alter_dopis_kategorija'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dopis',
            name='status',
        ),
    ]
