# Generated by Django 5.2.7 on 2026-02-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evidencija", "0012_merge_20260216_1121"),
        ("evidencija", "0012_remove_dopis_status"),
    ]

    operations = []
